kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim
spec:
  storageClassName: demo # Should mutch the storage class name in the persistance volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
